spring:
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: admin
    password: authdb_password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none
  sql:
    init:
      platform: h2

logging:
  file:
    path: /var/logs
    name: logsOfAuthService.log
  level:
    root: info
    org:
      springframework:
        security: info

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000